language: android
disk: trusty
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
before_install:
- openssl aes-256-cbc -K $encrypted_c645f568b551_key -iv $encrypted_c645f568b551_iv
  -in $TRAVIS_BUILD_DIR/keys/buffrapp.jks.enc -out $TRAVIS_BUILD_DIR/buffrapp.jks -d
script:
- "./gradlew clean build assembleDebug --stacktrace"
before_deploy:
- cd app/build/outputs/apk/debug
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $TRAVIS_BUILD_DIR/buffrapp.jks
  -storepass $storepass -keypass $storepass app-debug-unsigned.apk buffrapp
- jarsigner -verify app-debug-unsigned.apk
- "${ANDROID_HOME}/build-tools/28.0.3/zipalign -v 4 app-debug-unsigned.apk $HOME/BuffRapp-debug-unsigned.apk"
deploy:
  provider: releases
  api_key:
    secure: EMPg5ZpMvtuVrkVQZSK7jsjwjcaLWMhMQnmPORTS8aTxu/XIxYkREz2oBoC93adCJpxo98Uu+esQJyABzwkahA0ypdku89Ommjjb/8rRmirgL6wgnFeNY3Cj92u2LFxucyj3c+A1Ojs2qCDc7zKaLMXVIYaFzAKyU39yhyM/7nO5hwKd3RX4zXDoqn2K1aXHaJIwOksj8zgmG0YMKPNl5uSGTEnA1N2FI5RRqru8Qwl2suicVMZFLXfEeetTIoVyr/ns3AnV6MAeDJIDsaqMsgAl51PHyWpSrnQGQJK0dqlgHOoGuEsLmc23m0+suBc+vsHfkFJcnsOc88hADoO0biz3uw+rGN4otr3gs/giUCCj37Le7H2TrbgDTTj9bT9lfXUGwdP08l3UHxsvfhHHai7GaUH6vZnE+PCUZf+YIhvkXJj3FA8H2xTyiSspHAUVjMaU9ukTWLPLbvzRnkI2UVkJIUPJ+Yy2Jdn1oL7sBVlAfC8m3C4+YXv+tvL8niHAh9M4QB6XpO7yLyou4TBxsmrgpI3miXdMSxnZBKHpgdwW4r3mZ2WIkkPjcK5+tD6AUxPdBsMpKZLPM1oRCDjdZT71q9S2K2IXmnjMZjs/4Ts+mW8tVeX5bJBwtoOCb60zi+M2zUcIi0g/9ZJEw+lNgzZE03Ls7nlUmlazlnKsigM=
  file: $HOME/BuffRapp-debug-unsigned.apk
  on:
    repo: buffrapp/buffrapp_android
env:
  global:
    secure: QE/m83wAavqrQbdE5TSy5gVLhYx2wJau3yTx+Jg1A0yXNRX+Mu7b9s7ZzUYENHQlfVmh8+dbIxQor0hw1o5Qk7Kg88XuO25V3MRiLQV7H7DhBmSp/5Gc4qIqYcS0FeSVYEQB9L3fNvT9YEDC5NUTgnk5uybnah1Ug8oKcjahZp7Jn6Y/YH2SSOEL7KjAJE7YoQN4kr0KdjY281kSWZssoI96OnXM4qBjW0l8Z0CUaqZDfBAHM9bcQw2d/pR9r4i+X72Ooqm7iurybMm0SDNQSU+yWpr4tmIt/4NDDGbkId2rPCVn7QfaeagIo7G41eIdqKueXFUI0j8tLS/qcMM5KHtA/o1m66JJbE3fcasK+vFeYZwnbtyq7YjDCYePq76gyDzkDYZZ0oD1sxJ6B/LUGeWvP2hYuZ8z1zQmq2/0hcd1a3vi/CTYYSoUB0RN1dsX0/RtNTqpqDu2f/UGRjbRTDRTFPpQrhs5jZH7KcWV75d0xMCDuYud8p1bzW/xjJvNV5x1XlYE6c1WsUvMVJu5ukXCl8vIfbgdPtvZKkSeVp3+Lt5w+K+QBYrGoHQgaBO85PQLXzsN5kWfQ06EL+Pennq/eBThS/RWzEWrUpJv4+9wP9ajj9JPd/cJtRO/KKe9pE3BsKyHR41Cnk2wCUq6+BJjDjVYth0Nj/emzgoZPFM=
