name: BuffRApp for Android CI
on: [push]

jobs:
  build:
    name: BuffRApp mainline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decrypt files
        run: ./.github/scripts/decrypt_keys.sh
        env:
          STOREPASS: ${{ secrets.STOREPASS }}
      - name: Patch to disable signing of debug builds
        run: ./.github/scripts/nosignature.sh
      - name: Build with Gradle
        run: ./gradlew clean build assembleDebug --stacktrace
      - name: Sign the build
        run: ./.github/scripts/signbuild.sh
        env:
          STOREPASS: ${{ secrets.STOREPASS }}
      - name: Upload release
        run: ./.github/scripts/uploadrelease.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
